name: Build Firmware
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Fetch Submodules Manually
        run: |
          git submodule init
          git submodule update --init --recursive

      - name: Install Compiler
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi cmake ninja-build

      - name: Force Disable Picotool
        run: |
          echo "set(DISABLE_PICOTOOL ON)" >> CMakeLists.txt
          echo "set(PICO_NO_PICOTOOL ON)" >> CMakeLists.txt

      - name: Kill Duplicate Definitions
        run: |
          rm -f hid_pid.h
          touch hid_pid.h

      - name: Compile
        run: |
          mkdir build && cd build
          cmake -G "Ninja" -DPICO_SDK_FETCH_FROM_GIT=on ..
          ninja

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: picowinder-clean
          path: build/*.uf2
