/home/runner/work/picowinder_no_pullback/picowinder_no_pullback/usb_descriptors.h:694:15: note: in expansion of macro 'HID_USAGE_PID_PARAM_BLOCK_POOLS_REPORT'
  694 |     HID_USAGE(HID_USAGE_PID_PARAM_BLOCK_POOLS_REPORT), \
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/picowinder_no_pullback/picowinder_no_pullback/usb_descriptors.c:108:5: note: in expansion of macro 'SIDEWINDER_REPORT_DESC_FEATURE_POOL_REPORT'
  108 |     SIDEWINDER_REPORT_DESC_FEATURE_POOL_REPORT          (HID_REPORT_ID(REPORT_ID_FEATURE_POOL_REPORT)),
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
<command-line>: error: 'HID_USAGE_PID_RAM_POOL_SIZE_REPORT' undeclared here (not in a function); did you mean 'HID_USAGE_PID_RAM_POOL_SIZE'?
/home/runner/work/picowinder_no_pullback/picowinder_no_pullback/target_sdk/lib/tinyusb/src/class/hid/hid.h:535:35: note: in definition of macro 'HID_REPORT_DATA_1'
  535 | #define HID_REPORT_DATA_1(data) , data
      |                                   ^~~~
/home/runner/work/picowinder_no_pullback/picowinder_no_pullback/target_sdk/lib/tinyusb/src/class/hid/hid.h:672:35: note: in expansion of macro 'HID_REPORT_ITEM'
  672 | #define HID_USAGE(x)              HID_REPORT_ITEM(x, RI_LOCAL_USAGE, RI_TYPE_LOCAL, 1)
      |                                   ^~~~~~~~~~~~~~~
/home/runner/work/picowinder_no_pullback/picowinder_no_pullback/usb_descriptors.h:699:9: note: in expansion of macro 'HID_USAGE'
  699 |         HID_USAGE(HID_USAGE_PID_RAM_POOL_SIZE), \
      |         ^~~~~~~~~
/home/runner/work/picowinder_no_pullback/picowinder_no_pullback/usb_descriptors.h:699:19: note: in expansion of macro 'HID_USAGE_PID_RAM_POOL_SIZE'
  699 |         HID_USAGE(HID_USAGE_PID_RAM_POOL_SIZE), \
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/picowinder_no_pullback/picowinder_no_pullback/usb_descriptors.c:108:5: note: in expansion of macro 'SIDEWINDER_REPORT_DESC_FEATURE_POOL_REPORT'
  108 |     SIDEWINDER_REPORT_DESC_FEATURE_POOL_REPORT          (HID_REPORT_ID(REPORT_ID_FEATURE_POOL_REPORT)),
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/picowinder_no_pullback/picowinder_no_pullback/usb_descriptors.h:709:19: error: 'HID_USAGE_PID_SIMULTANEOUS_EFFECTS_MAX' undeclared here (not in a function)
  709 |         HID_USAGE(HID_USAGE_PID_SIMULTANEOUS_EFFECTS_MAX), \
      |                   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/picowinder_no_pullback/picowinder_no_pullback/target_sdk/lib/tinyusb/src/class/hid/hid.h:535:35: note: in definition of macro 'HID_REPORT_DATA_1'
  535 | #define HID_REPORT_DATA_1(data) , data
      |                                   ^~~~
/home/runner/work/picowinder_no_pullback/picowinder_no_pullback/target_sdk/lib/tinyusb/src/class/hid/hid.h:672:35: note: in expansion of macro 'HID_REPORT_ITEM'
  672 | #define HID_USAGE(x)              HID_REPORT_ITEM(x, RI_LOCAL_USAGE, RI_TYPE_LOCAL, 1)
      |                                   ^~~~~~~~~~~~~~~
/home/runner/work/picowinder_no_pullback/picowinder_no_pullback/usb_descriptors.h:709:9: note: in expansion of macro 'HID_USAGE'
  709 |         HID_USAGE(HID_USAGE_PID_SIMULTANEOUS_EFFECTS_MAX), \
      |         ^~~~~~~~~
/home/runner/work/picowinder_no_pullback/picowinder_no_pullback/usb_descriptors.c:108:5: note: in expansion of macro 'SIDEWINDER_REPORT_DESC_FEATURE_POOL_REPORT'
  108 |     SIDEWINDER_REPORT_DESC_FEATURE_POOL_REPORT          (HID_REPORT_ID(REPORT_ID_FEATURE_POOL_REPORT)),
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/runner/work/picowinder_no_pullback/picowinder_no_pullback/usb_descriptors.c: In function 'tud_descriptor_string_cb':
/home/runner/work/picowinder_no_pullback/picowinder_no_pullback/usb_descriptors.c:190:25: warning: implicit declaration of function 'board_usb_get_serial' [-Wimplicit-function-declaration]
  190 |             chr_count = board_usb_get_serial(_desc_str + 1, 32);
      |                         ^~~~~~~~~~~~~~~~~~~~
[62/93] Building ASM object CMakeFiles/picowinder.dir/target_sdk/src/rp2_common/pico_mem_ops/mem_ops_aeabi.S.obj
[63/93] Building C object CMakeFiles/picowinder.dir/target_sdk/src/rp2_common/pico_malloc/pico_malloc.c.obj
[64/93] Building C object CMakeFiles/picowinder.dir/target_sdk/src/rp2_common/pico_printf/printf.c.obj
[65/93] Building C object CMakeFiles/picowinder.dir/target_sdk/src/rp2_common/pico_float/float_math.c.obj
[66/93] Building C object CMakeFiles/picowinder.dir/target_sdk/src/rp2_common/pico_double/double_math.c.obj
ninja: build stopped: subcommand failed.
Error: Process completed with exit code 1.
